[package]
name = "from_into"
version = "0.1.0"
authors = ["Alexx Roche <notice-dev@alexx.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
